### ISSUE TITLE
Incorrect SNAPSHOT version checking logic for `in` script.

### ISSUE THREAD

**Issue by shinmyung0** [patrickcrocker/maven-resource#12]
I noticed that the implicit `get` after a `put` for my `snapshot` artifacts were breaking. I did some digging and the reason was that the implicit `get` step was looking for the snapshot version artifacts from the `release_url`. This is due to a typo in the `in` script for checking whether a version is a snapshot version.

`in` script uses an `&&` 
https://github.com/patrickcrocker/maven-resource/blob/master/assets/in#L89

`out` script uses an `||` which is the correct behavior.
 https://github.com/patrickcrocker/maven-resource/blob/master/assets/out#L106

I fixed my pipeline scripts to use `1.3.2` instead of `latest` for now. Thanks again for your great work!

**Comment by patrickcrocker** [comment]
This is now fixed and the 1.3.3 release has been yanked.  Thanks!

See: https://github.com/Pivotal-Field-Engineering/maven-resource/releases/tag/v1.3.4
