### ISSUE TITLE
does not work with Concourse 3.9

### ISSUE THREAD

**Issue by making** [patrickcrocker/maven-resource#18]
After updating to 3.9.0, maven-resource does not seem to work.

This is what I got in case of 3.8.0 with no problem
![image](https://user-images.githubusercontent.com/106908/36207112-2373c6a6-11d8-11e8-9f15-f82fa0d1d06c.png)

This is 3.9.0's (no log 😢)
![image](https://user-images.githubusercontent.com/106908/36207156-43f4240c-11d8-11e8-8e0a-5af125bc407f.png)

Here is my pipleline
https://github.com/making/fizz-buzz/blob/develop/ci/pipeline.yml

https://concourse.ik.am/teams/dev/pipelines/fizz-buzz/jobs/upload-to-nexus-snapshots/builds/6
I'd appreciate it if you could look into it.
Thanks

**Comment by shinji62** [comment]
Issue and workaround is there https://github.com/concourse/concourse/issues/2042

Please check it.

**Comment by making** [comment]
That workarround works for me.
I'm closing this issue as this is not resource issue.
Thanks
