### ISSUE TITLE
check doesn't react to new snapshot of same version

### ISSUE THREAD

**Issue by mbjelac** [patrickcrocker/maven-resource#5]
I expected this resource to recognize when a new snapshot version is available.

I realize each new version of the snapshot has the same `project.version` value in the POM, but a timestamp should also be available somewhere in the metadata?

Using that timestamp it would be possible to recognize that the current snapshot has a larger timestamp than the last, so it is new.

**Comment by patrickcrocker** [comment]
Opened Tracker story:
https://www.pivotaltracker.com/n/projects/1789539/stories/142521589

**Comment by patrickcrocker** [comment]
I think I've got this resolved. Please checkout version 1.2.0-rc.13 of the maven-resource.  For an example of its usage, checkout this pipeline: https://github.com/patrickcrocker/maven-snapshot-ci

Be sure to add in `snapshot_url` to your resource config. You'll also note that the `version` file is now optional (we now default to the version from the pom.xml)

**Comment by mbjelac** [comment]
IT WORKS!!!

Verified:

1. Version file not necessary.
2. Resource trigger works when publishing new snapshot of same version.

Many thanks @patrickcrocker !

**Comment by patrickcrocker** [comment]
Version 1.2.0 has been published!  Please switch to use 1.2.0 (or `latest`) as the rc.13 will be cleaned up in a week or so.
